# Generated by Django 2.0.2 on 2018-02-27 12:16

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dia_vencimento', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30)])),
                ('tipo', models.CharField(max_length=40)),
                ('data_criacao', models.DateField(default=django.utils.timezone.now)),
                ('dias_periodo', models.PositiveIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
