# Generated by Django 2.0.2 on 2018-03-01 18:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('dia_vencimento', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30)])),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('referente', models.DateTimeField(auto_now_add=True)),
                ('paga', models.BooleanField(default=False)),
                ('observacao', models.TextField(blank=True)),
                ('despesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='www.Despesa')),
            ],
        ),
    ]
