# Generated by Django 2.0.2 on 2018-02-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='observacao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='despesa',
            name='periodica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='despesa',
            name='repeticao_anual',
            field=models.BooleanField(default=False),
        ),
    ]
