# Generated by Django 2.0.2 on 2018-03-02 13:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0002_conta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despesa',
            name='inicio',
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='meses_periodo',
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='termino',
        ),
        migrations.AddField(
            model_name='conta',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='despesa',
            name='mes_inicio',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='despesa',
            name='mes_termino',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='conta',
            name='referente',
            field=models.DateTimeField(),
        ),
    ]
