# Generated by Django 2.0.2 on 2018-02-27 13:06

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0002_auto_20180227_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despesa',
            name='dias_periodo',
        ),
        migrations.AddField(
            model_name='despesa',
            name='inicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='despesa',
            name='meses_periodo',
            field=models.PositiveIntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(11)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='despesa',
            name='termino',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
