# Generated by Django 2.0.2 on 2018-02-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0003_auto_20180227_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='meses_periodo',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)], null=True),
        ),
    ]
