# Generated by Django 2.0.2 on 2018-03-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0005_auto_20180302_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='data_alteracao_pagamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
