# Generated by Django 2.0.2 on 2018-03-07 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0007_despesa_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='despesa',
            old_name='user',
            new_name='usuario',
        ),
    ]
