# Generated by Django 2.0.2 on 2018-03-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0008_auto_20180307_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='pendente_cadastro_conta',
            field=models.BooleanField(default=True),
        ),
    ]
