# Generated by Django 2.0.2 on 2018-03-16 18:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0010_auto_20180312_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='despesa',
            old_name='valor',
            new_name='estimativa',
        ),
        migrations.AlterField(
            model_name='despesa',
            name='mes_inicio',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)]),
        ),
    ]
